Repository polyand/online-store-team, pull requests merged in 2023-01, with the labels that each got.

#34 Store_13 - Feat: Create modal window
  package-lock.json
  src/assets/img/ae-logo.png
  src/assets/img/mc-logo.png
  src/assets/img/unknown-card.png
  src/assets/img/v-logo.png
  src/components/modal/index.ts
  src/components/modal/modal-utils/del-modal-query.ts
  src/components/modal/modal-utils/display-card.ts
  src/components/modal/modal-utils/show-warning-msg.ts
  src/components/modal/modal-utils/toggle-modal.ts
  src/components/modal/modal-utils/validate-adress.ts
  src/components/modal/modal-utils/validate-card-cvv.ts
  src/components/modal/modal-utils/validate-card-date.ts
  src/components/modal/modal-utils/validate-card-num.ts
  src/components/modal/modal-utils/validate-email.ts
  src/components/modal/modal-utils/validate-name.ts
  src/components/modal/modal-utils/validate-tel.ts
  src/components/modal/modal-utils/warning-texts.ts
  src/components/modal/modal.html
  src/components/modal/modal.scss
  src/components/modal/modal.ts
  src/index.html
  src/index.ts
  src/pages/cart/cart-utils/set-modal-query.ts
  src/pages/cart/cart.ts
  src/styles/_main.scss
  src/styles/_variables.scss
  src/utils/getInputElement.ts
  src/utils/queries.ts
  src/utils/types.ts
Labels: new feature

#35 Feature/store 18/setting up home page filters
  src/pages/home/home-utils/checkUseFilters.ts
  src/pages/home/home-utils/correctionCheckboxItemQuantity.ts
  src/pages/home/home-utils/createCheckboxFilter.ts
  src/pages/home/home-utils/createProductsList.ts
  src/pages/home/home-utils/createRangeFilters.ts
  src/pages/home/home-utils/filtredProducts.ts
  src/pages/home/home-utils/useCheckboxFilter.ts
  src/pages/home/home-utils/useRangeFilter.ts
  src/pages/home/home.html
  src/pages/home/home.scss
  src/pages/home/home.ts
  src/utils/helpersArray.ts
  src/utils/types.ts
Labels: new feature

#37 Store_14 - Feat: Add product info page
  src/_redirects
  src/index.html
  src/pages/product/index.ts
  src/pages/product/product-utils/add-product-to-cart.ts
  src/pages/product/product-utils/change-image.ts
  src/pages/product/product-utils/display-cart-button.ts
  src/pages/product/product-utils/drop-product-from-cart.ts
  src/pages/product/product-utils/fill-product-page.ts
  src/pages/product/product-utils/get-buy-now.ts
  src/pages/product/product.html
  src/pages/product/product.scss
  src/pages/product/product.ts
  src/styles/_variables.scss
  src/utils/addToCart.ts
  src/utils/dropFromCart.ts
  src/utils/getGlobalProductId.ts
  src/utils/router.ts
  src/utils/saveCart.ts
Labels: new feature, new page

#39 Store_19 Feat: Setting up home page text filter and data sort
  src/data/data.json
  src/pages/home/home-utils/buildProductsList.ts
  src/pages/home/home-utils/checkTextFilter.ts
  src/pages/home/home-utils/createProductsList.ts
  src/pages/home/home-utils/createSortProducts.ts
  src/pages/home/home-utils/filtredProducts.ts
  src/pages/home/home-utils/searchProducts.ts
  src/pages/home/home-utils/useSortProducts.ts
  src/pages/home/home-utils/useTextFilter.ts
  src/pages/home/home.ts
  src/utils/types.ts
Labels: new feature

#40 Store_20 - Fix: fixing small bugs and problems
  src/components/header/header-utils/jump-cart-page.ts
  src/components/header/header-utils/jump-home-page.ts
  src/components/header/header.ts
  src/components/modal/modal-utils/show-warning-msg.ts
  src/pages/cart/cart-utils/create-product-item.ts
  src/pages/cart/cart.scss
  src/pages/home/home.ts
  src/utils/productPageNavigator.ts
Labels: bugfix

#43 Store_21 - Feat: Query parameters
  src/index.ts
  src/pages/home/home-utils/changeViewProducts.ts
  src/pages/home/home-utils/checkTextFilter.ts
  src/pages/home/home-utils/copyLink.ts
  src/pages/home/home-utils/createProductsList.ts
  src/pages/home/home-utils/createRangeFilters.ts
  src/pages/home/home-utils/createSortProducts.ts
  src/pages/home/home-utils/filtredProducts.ts
  src/pages/home/home-utils/queriesHome.ts
  src/pages/home/home-utils/resetFilters.ts
  src/pages/home/home-utils/searchProducts.ts
  src/pages/home/home-utils/setCheckboxFilters.ts
  src/pages/home/home-utils/setFilters.ts
  src/pages/home/home-utils/setRangeFilters.ts
  src/pages/home/home-utils/setSortProducts.ts
  src/pages/home/home-utils/setTextFilter.ts
  src/pages/home/home-utils/setViewProducts.ts
  src/pages/home/home-utils/useCheckboxFilter.ts
  src/pages/home/home-utils/useTextFilter.ts
  src/pages/home/home.scss
  src/pages/home/home.ts
  src/styles/_variables.scss
  src/utils/queries copy.ts
  src/utils/queries.ts
  src/utils/types.ts
Labels: new feature

#45 Store_23 - Fix: open/close modal window
  src/components/modal/modal-utils/del-modal-query.ts
  src/components/modal/modal-utils/show-warning-msg.ts
  src/pages/cart/cart-utils/set-modal-query.ts
  src/utils/queries copy.ts
  src/utils/queriesModal.ts
Labels: bugfix

#47 Store_24 - Feat: Jump to product pages and add/remove product
  src/pages/home/home-utils/addRemoveProduct.ts
  src/pages/home/home-utils/buildProductsList.ts
  src/pages/home/home-utils/createProductsList.ts
  src/pages/home/home-utils/jumpProductPage.ts
  src/pages/home/home.scss
Labels: new feature

#49 Store_25 - Refactor: Update settings up query parameters
  src/pages/home/home-utils/changeViewProducts.ts
  src/pages/home/home-utils/createRangeFilters.ts
  src/pages/home/home-utils/createSortProducts.ts
  src/pages/home/home-utils/useTextFilter.ts
  src/utils/queries.ts
Labels: refactor

#51 Store_26 - Fix: Fix bugs on home page
  src/assets/img/favicon.svg
  src/components/header/header.scss
  src/index.html
  src/pages/home/home-utils/addRemoveProduct.ts
  src/pages/home/home-utils/changeViewProducts.ts
  src/pages/home/home-utils/correctionCheckboxItemQuantity.ts
  src/pages/home/home-utils/createCheckboxFilter.ts
  src/pages/home/home-utils/createSortProducts.ts
  src/pages/home/home-utils/jumpProductPage.ts
  src/pages/home/home-utils/searchProducts.ts
  src/pages/home/home.scss
  src/utils/getHtmlCollection.ts
Labels: bugfix

#54 Store_27 - Feature: Add products to the catalog
  src/data/assets/dining room/chairs/purhus/1.jpg
  src/data/assets/dining room/chairs/purhus/2.jpg
  src/data/assets/dining room/chairs/purhus/3.jpg
  src/data/assets/dining room/chairs/purhus/thumbnail.jpg
  src/data/assets/dining room/tables/aabenraa/1.jpg
  src/data/assets/dining room/tables/aabenraa/2.jpg
  src/data/assets/dining room/tables/aabenraa/3.jpg
  src/data/assets/dining room/tables/aabenraa/thumbnail.jpg
  src/data/assets/dining room/tables/gadeskov/1.jpg
  src/data/assets/dining room/tables/gadeskov/2.jpg
  src/data/assets/dining room/tables/gadeskov/3.jpg
  src/data/assets/dining room/tables/gadeskov/thumbnail.jpg
  src/data/assets/storage/cabinet/haldager/1.jpg
  src/data/assets/storage/cabinet/haldager/2.jpg
  src/data/assets/storage/cabinet/haldager/3.jpg
  src/data/assets/storage/cabinet/haldager/thumbnail.jpg
  src/data/assets/storage/cabinet/reflect/1.jpg
  src/data/assets/storage/cabinet/reflect/2.jpg
  src/data/assets/storage/cabinet/reflect/3.jpg
  src/data/assets/storage/cabinet/reflect/thumbnail.jpg
  src/data/assets/storage/cabinet/skals/1.jpg
  src/data/assets/storage/cabinet/skals/2.jpg
  src/data/assets/storage/cabinet/skals/3.jpg
  src/data/assets/storage/cabinet/skals/thumbnail.jpg
  src/data/assets/storage/shelving/broby/1.jpg
  src/data/assets/storage/shelving/broby/2.jpg
  src/data/assets/storage/shelving/broby/3.jpg
  src/data/assets/storage/shelving/broby/thumbnail.jpg
  src/data/assets/storage/shelving/horsens/1.jpg
  src/data/assets/storage/shelving/horsens/2.jpg
  src/data/assets/storage/shelving/horsens/3.jpg
  src/data/assets/storage/shelving/horsens/thumbnail.jpg
  src/data/assets/storage/shelving/jannerup/1.jpg
  src/data/assets/storage/shelving/jannerup/2.jpg
  src/data/assets/storage/shelving/jannerup/3.jpg
  src/data/assets/storage/shelving/jannerup/thumbnail.jpg
  src/data/assets/storage/shelving/vandborg/1.jpg
  src/data/assets/storage/shelving/vandborg/2.jpg
  src/data/assets/storage/shelving/vandborg/3.jpg
  src/data/assets/storage/shelving/vandborg/thumbnail.jpg
  src/data/data.json
  src/index.html
  src/pages/home/home-utils/checkUseFilters.ts
Labels: new feature

#52 Store_22 - Feature: Write unit tests
  .github/workflows/actions.yml
  jest.config.js
  package-lock.json
  package.json
  src/pages/cart/cart-utils/trigger-empty-cart.ts
  test/addElement.test.ts
  test/compareNumeric.test.ts
  test/containsElement.test.ts
  test/getGlobalProductId.test.ts
  test/getProductById.test.ts
  test/getTotalAmount.test.ts
  test/getTotalCost.test.ts
  test/removeElement.test.ts
  test/triggerEmptyCart.test.ts
  test/validateCardDate.test.ts
  test/validateEmail.test.ts
Labels: documentation, new feature

#56 Store_28 - Refactor: clean code for get no implicit any errors
  package-lock.json
  package.json
  src/components/modal/modal-utils/show-warning-msg.ts
  src/data/assets/bedroom/beds/sallinge/3.jfif
  src/data/assets/dining room/chairs/jels/3.jpg
  src/data/assets/storage/wardrobe/jenslev/3.jpg
  src/data/data.json
  src/index.html
  src/pages/home/home-utils/checkTextFilter.ts
  src/pages/home/home-utils/checkUseFilters.ts
  src/pages/home/home-utils/correctionCheckboxItemQuantity.ts
  src/pages/home/home-utils/createCheckboxFilter.ts
  src/pages/home/home-utils/createRangeFilters.ts
  src/pages/home/home-utils/createSortProducts.ts
  src/pages/home/home-utils/filtredProducts.ts
  src/pages/home/home-utils/setCheckboxFilters.ts
  src/pages/home/home-utils/setFilters.ts
  src/pages/home/home-utils/setRangeFilters.ts
  src/pages/home/home-utils/useCheckboxFilter.ts
  src/pages/home/home-utils/useRangeFilter.ts
  src/pages/home/home-utils/useSortProducts.ts
  src/utils/queries.ts
  src/utils/types.ts
  test/containsElement.test.ts
  test/getGlobalProductId.test.ts
  test/triggerEmptyCart.test.ts
  test/validateCardDate.test.ts
  test/validateEmail.test.ts
  tsconfig.json
  webpack.config.js
Labels: refactor

#59 Hotfix: add classes to cart.ts, home.ts and product.ts
  src/pages/cart/cart.ts
  src/pages/cart/index.ts
  src/pages/home/home.ts
  src/pages/home/index.ts
  src/pages/product/index.ts
  src/pages/product/product.ts
  src/utils/router.ts
Labels: refactor
